In [ ]:
import numpy   as np 
import scipy.misc # to visualize only  
x = np.loadtxt("../../data/train_x.csv", delimiter=",") # load from text 
y = np.loadtxt("../../data/train_y.csv", delimiter=",") 
x = x.reshape(-1, 64, 64) # reshape 
y = y.reshape(-1, 1) 
np.save(p+"X_train",x)
np.save(p+"y_train",y)
print("X.shape",x.shape, "Y.shape",y.shape)
scipy.misc.imshow(x[0])

In [14]:
import numpy as np
from numpy import exp, array, random, dot

class FeedForwardNeuralNetwork():
    #Nlayer must be >=2
    def __init__(self,NLayer,Nneuron,ranSeed,Ninput,Noutput,bias):
        #specify the number of hidden layers , number of neurons needed per layer, number of weights per neuron
        #ranSeed specify the random seed used in initializing weights
        #activation specified what activation function is to be used, pass in 0 to use default sigmoid function
        #-------------------------------
        np.random.seed(ranSeed)
        self.bias = bias
        self.Nneuron = Nneuron
        self.Ninput = Ninput
        self.Noutput = Noutput
        self.NLayer = NLayer
        #input weights
        self.InputWeight = np.random.rand(Nneuron,Ninput)
        #this is weight for neurons from hidden layer 1 to (n-1)
        self.neurons = np.random.rand(NLayer-1,Nneuron,Nneuron)
        #store output of each layer
        self.O = np.random.rand(NLayer,Nneuron)
        #the weight for the last layer of neurons
        self.OutputWeight = np.random.rand(Nneuron,Noutput)
        #encoding output layer with multi-class domains, each output neuron represents a discrete output value
        #see as an classification task
        self.output = np.random.rand(Noutput)
    
    #default activation function, normalize input into 0 and 1
    # normalise them between 0 and 1.
    def sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    def sigmoid_derivative(self, x):
        return x * (1 - x)

    #train the neural network
    #can change learning rate
    def train(self, num_training_example, training_inputs, training_outputs, num_iteration, learning_rate):
        for iteration in xrange(num_iteration):
            for i in range(0,num_training_example):
                #---------------------------------------------
                #need a output layer special gamma
                #-------------------------------------------
                gammaOutput = np.zeros(self.Noutput)
                # gamma is the error correction for all neurons in NN
                # gamma values are used to backpropagate
                gamma = np.zeros((self.NLayer,self.Nneuron))
                # Forward pass
                output = self.forward(training_inputs[i])
                #compute differnce between output and expected output
                error = np.ones(self.Noutput)
                #compute corrections
                # first calculate correction in the output layer
                for k in range(0,self.Noutput):
                    error[k] = training_outputs[i][k]-self.output[k]
                    gammaOutput[k] = self.sigmoid(self.output[k])*error[k]
                    #calculate the gamma values for the last hidden layer
                    #And update weights for output layer
                    for z in range(0,self.Nneuron):
                        gamma[self.NLayer-1][k] = self.sigmoid(self.O[self.NLayer-1][k])*dot(gammaOutput,self.OutputWeight[z])
                        self.OutputWeight[z][k] = self.OutputWeight[z][k] + (learning_rate*gammaOutput[k]*
                                                                              self.O[self.NLayer-1][z])
                #--------------------------------------
                #calculate the backprop for hidden layer
                #j is counting the current layer
                #z is counting the neuron position
                #propagate gamma values
                for j in range(self.NLayer-2,-1,-1):
                    for z in range(0,self.Nneuron):
                        #multiple the derivative with all the connected neuron's gamma
                        #SumGamma will compute all the propagated gammas
                        gamma[j][z] = self.sigmoid(self.O[j][z])*(self.SumGamma(gamma,j,z))
                        #update the weights now
                        for k in range(0,self.Nneuron):
                            self.neurons[j][z][k] = self.neurons[j][z][k] + (learning_rate*gamma[j][z]*
                            self.O[j][k])
                            
                #---------------------------------------
        
    #compute the propagated gamma of a neuron
    def SumGamma(self,gamma,Layer,position):
        output = 0.0
        output = output + dot(gamma[Layer+1],self.neurons[Layer][position])
        return output
                
    # pass input through all the layers until the output layer
    def forward(self, inputs):        
        #first pass from input layer to hidden layer
        current = np.ones(self.Nneuron)
        for i in range(0,self.Nneuron):
            current[i] = self.sigmoid(dot(inputs,self.InputWeight[i])+self.bias)
            self.O[0][i] = current[i]
        #passing through hidden layers
        for i in range(0,self.NLayer-1):
            for j in range(0,self.Nneuron):
                current[j] = self.sigmoid(dot(self.O[i],self.neurons[i][j])+self.bias)
            self.O[i+1] = np.copy(current)
        #now from hidden layer to output layer
        #the weight for the last hidden layer is the weight for the output layer 
        #---------------------------------------------------------------
        for i in range(0,self.Noutput):
            self.output[i]= self.sigmoid(dot(current,self.OutputWeight[:,i])+self.bias)
        #----------------------------------------------------------------
        print (self.output)
        
        
if __name__ == "__main__":

    #Intialise a single neuron neural network.
    #def __init__(self,NLayer,Nneuron,ranSeed,Ninput,Noutput,bias):
    neural_network = FeedForwardNeuralNetwork(2,4096,1,4096,40,0.001)
    #def train(self, num_training_example, training_inputs, training_outputs, num_iteration, learning_rate):
    neural_network.train(,x,y,,0.1)
    
    
    

    #print "Random starting synaptic weights: "
    #print neural_network.synaptic_weights

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    #training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    #training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    #neural_network.train(training_set_inputs, training_set_outputs, 10000)
    # Test the neural network with a new situation.

[ 0.91424739  0.89692967  0.95911598]
[ 0.91589171  0.89921494  0.94788148]
[ 0.91754715  0.90149605  0.93409607]
[ 0.91921222  0.90377232  0.91740748]
[ 0.92088457  0.90604184  0.89751756]
[ 0.92256099  0.90830149  0.87423178]
[ 0.92423739  0.91054692  0.84751086]
[ 0.92590888  0.91277272  0.81751274]
[ 0.92756993  0.91497262  0.78461095]
[ 0.92921463  0.91713983  0.74937886]
[ 0.93083704  0.91926748  0.71253835]
[ 0.93243145  0.92134906  0.67488301]
[ 0.93399279  0.92337877  0.63719424]
[ 0.93551676  0.92535187  0.60016945]
[ 0.93700003  0.92726477  0.56437503]
[ 0.93844018  0.92911509  0.53022729]
[ 0.93983571  0.93090155  0.49799679]
[ 0.94118589  0.93262384  0.46782764]
[ 0.94249064  0.93428243  0.43976356]
[ 0.94375038  0.93587841  0.41377455]
[ 0.94496594  0.93741334  0.38978047]
[ 0.94613841  0.93888909  0.36767009]
[ 0.94726907  0.94030772  0.34731554]
[ 0.94835935  0.94167144  0.32858247]
[ 0.94941073  0.94298251  0.31133706]
[ 0.95042472  0.94424319  0.29545036]
[ 0.95140285

[ 0.99139785  0.99126391  0.01577482]
[ 0.99142593  0.99129292  0.01571132]
[ 0.99145381  0.99132174  0.01564833]
[ 0.99148151  0.99135035  0.01558586]
[ 0.99150902  0.99137877  0.01552389]
[ 0.99153634  0.991407    0.01546242]
[ 0.99156349  0.99143503  0.01540144]
[ 0.99159045  0.99146288  0.01534095]
[ 0.99161724  0.99149053  0.01528094]
[ 0.99164384  0.991518    0.0152214 ]
[ 0.99167028  0.99154528  0.01516233]
[ 0.99169654  0.99157239  0.01510373]
[ 0.99172263  0.99159931  0.01504558]
[ 0.99174854  0.99162605  0.01498789]
[ 0.9917743   0.99165262  0.01493064]
[ 0.99179988  0.99167901  0.01487384]
[ 0.9918253   0.99170522  0.01481747]
[ 0.99185056  0.99173127  0.01476154]
[ 0.99187565  0.99175714  0.01470603]
[ 0.99190059  0.99178285  0.01465095]
[ 0.99192536  0.99180839  0.01459628]
[ 0.99194998  0.99183377  0.01454203]
[ 0.99197445  0.99185898  0.01448818]
[ 0.99199876  0.99188403  0.01443474]
[ 0.99202292  0.99190892  0.01438169]
[ 0.99204692  0.99193366  0.01432904]
[ 0.99207078

[ 0.99580608  0.99577433  0.00682431]
[ 0.99581252  0.99578086  0.00681266]
[ 0.99581894  0.99578737  0.00680105]
[ 0.99582534  0.99579386  0.00678947]
[ 0.99583172  0.99580033  0.00677794]
[ 0.99583807  0.99580678  0.00676645]
[ 0.99584441  0.99581321  0.00675499]
[ 0.99585073  0.99581962  0.00674357]
[ 0.99585703  0.99582601  0.0067322 ]
[ 0.99586331  0.99583238  0.00672086]
[ 0.99586957  0.99583874  0.00670956]
[ 0.99587582  0.99584507  0.0066983 ]
[ 0.99588204  0.99585138  0.00668707]
[ 0.99588824  0.99585767  0.00667589]
[ 0.99589443  0.99586395  0.00666474]
[ 0.9959006   0.9958702   0.00665363]
[ 0.99590675  0.99587644  0.00664255]
[ 0.99591287  0.99588265  0.00663152]
[ 0.99591899  0.99588885  0.00662052]
[ 0.99592508  0.99589503  0.00660955]
[ 0.99593115  0.99590119  0.00659862]
[ 0.99593721  0.99590733  0.00658773]
[ 0.99594325  0.99591345  0.00657688]
[ 0.99594926  0.99591956  0.00656606]
[ 0.99595527  0.99592565  0.00655528]
[ 0.99596125  0.99593171  0.00654453]
[ 0.99596722

[ 0.99696815  0.99695119  0.00478299]
[ 0.9969715   0.99695458  0.00477728]
[ 0.99697485  0.99695796  0.00477158]
[ 0.99697818  0.99696133  0.0047659 ]
[ 0.99698151  0.9969647   0.00476023]
[ 0.99698483  0.99696805  0.00475458]
[ 0.99698815  0.9969714   0.00474894]
[ 0.99699145  0.99697475  0.00474331]
[ 0.99699475  0.99697808  0.00473769]
[ 0.99699805  0.99698141  0.00473209]
[ 0.99700133  0.99698473  0.0047265 ]
[ 0.99700461  0.99698805  0.00472093]
[ 0.99700788  0.99699135  0.00471537]
[ 0.99701114  0.99699465  0.00470982]
[ 0.9970144   0.99699794  0.00470428]
[ 0.99701765  0.99700123  0.00469876]
[ 0.99702089  0.9970045   0.00469325]
[ 0.99702413  0.99700777  0.00468775]
[ 0.99702736  0.99701104  0.00468227]
[ 0.99703058  0.99701429  0.0046768 ]
[ 0.99703379  0.99701754  0.00467134]
[ 0.997037    0.99702078  0.00466589]
[ 0.9970402   0.99702402  0.00466046]
[ 0.99704339  0.99702725  0.00465504]
[ 0.99704658  0.99703047  0.00464963]
[ 0.99704976  0.99703368  0.00464424]
[ 0.99705293